tosca_definitions_version: tosca_simple_yaml_1_0

metadata:
  template_name: Proxmox
  template_author: Quali
  template_version: 1.0.0
  template_icon: proxmox.png

description: >
  sample deployment path file

imports:
  - cloudshell_standard: cloudshell_cloud_provider_standard_1_0_1.yaml

node_types:
#  vendor.resource.Proxmox Instance From QEMU Image 2G:
#    derived_from: cloudshell.nodes.CustomDeploymentOption
#    properties:
#      Target Node:
#        type: string
#        description: "Target node name. Only allowed if the original VM is on shared storage."
#        tags: [ user_input, editable_only_in_app_template, enable_hints ]
#      Image URL:
#        type: string
#        description: "QEMU Image URL that will be used as a source for
#        deploying a VM."
#        tags: [ user_input ]
#      Behavior during save:
#        type: string
#        description: "Determines the VM behavior when the sandbox is saved.
#        If Power off is selected, and the VM was powered on before the save,
#        then the VM will shut down for the duration of the save,
#        and then be powered on at the end."
#        constraints:
#          - valid_values: [ "Remain Powered On", "Power Off", "Inherited" ]
#        default: "Inherited"
#        tags: [ user_input ]
#      Auto Power On:
#        type: boolean
#        description: "Enables the automatic power on of an app following its deployment during reservation Setup."
#        default: true
#        tags: [ user_input ]
#      Auto Power Off:
#        type: boolean
#        description: "Enables the automatic power off of an app during reservation Teardown."
#        default: true
#        tags: [ ]
#      Wait for IP:
#        type: boolean
#        description: "If set to False the deployment will not wait for the VM to get an IP."
#        default: true
#        tags: [ user_input ]
#      Auto Delete:
#        type: boolean
#        description: "Enables automatic deletion of an app during reservation Teardown."
#        default: true
#        tags: [ ]
#      Autoload:
#        type: boolean
#        description: "Enables the automatic execution of the Autoload command during reservation Setup."
#        default: true
#        tags: [ user_input ]
#      Refresh IP Timeout:
#        type: integer
#        description: "Timeout for waiting when obtaining IP address (in seconds)"
#        default: 600
#        tags: [ ]
#      Autogenerated Name:
#        type: boolean
#        description: "If true the name would be generated by the Shell, otherwise it would be the same as App name."
#        default: true
#        tags: [ user_input ]
#    artifacts:
#      icon:
#        file: proxmox.png
#        type: tosca.artifacts.File

#  vendor.resource.Proxmox Instance From Container Image 2G:
#    derived_from: cloudshell.nodes.CustomDeploymentOption
#    properties:
#      Target Node:
#        type: string
#        description: "Target node name. Only allowed if the original VM is on shared storage."
#        tags: [ user_input, editable_only_in_app_template, enable_hints ]
#      Container Image:
#        type: string
#        description: "Proxmox Container name or URL that will be used as a source for
#        deploying a container."
#        tags: [ user_input, editable_only_in_app_template, enable_hints ]
#      Behavior during save:
#        type: string
#        description: "Determines the VM behavior when the sandbox is saved.
#        If Power off is selected, and the VM was powered on before the save,
#        then the VM will shut down for the duration of the save,
#        and then be powered on at the end."
#        constraints:
#          - valid_values: [ "Remain Powered On", "Power Off", "Inherited" ]
#        default: "Inherited"
#        tags: [ user_input ]
#      Auto Power On:
#        type: boolean
#        description: "Enables the automatic power on of an app following its deployment during reservation Setup."
#        default: true
#        tags: [ user_input ]
#      Auto Power Off:
#        type: boolean
#        description: "Enables the automatic power off of an app during reservation Teardown."
#        default: true
#        tags: [ ]
#      Wait for IP:
#        type: boolean
#        description: "If set to False the deployment will not wait for the VM to get an IP."
#        default: true
#        tags: [ user_input ]
#      Auto Delete:
#        type: boolean
#        description: "Enables automatic deletion of an app during reservation Teardown."
#        default: true
#        tags: [ ]
#      Autoload:
#        type: boolean
#        description: "Enables the automatic execution of the Autoload command during reservation Setup."
#        default: true
#        tags: [ user_input ]
#      Refresh IP Timeout:
#        type: integer
#        description: "Timeout for waiting when obtaining IP address (in seconds)"
#        default: 600
#        tags: [ ]
#      Autogenerated Name:
#        type: boolean
#        description: "If true the name would be generated by the Shell, otherwise it would be the same as App name."
#        default: true
#        tags: [ user_input ]
#    artifacts:
#      icon:
#        file: proxmox.png
#        type: tosca.artifacts.File

  vendor.resource.Proxmox Instance From VM 2G:
    derived_from: cloudshell.nodes.CustomDeploymentOption
    properties:
      Target Node:
        type: string
        description: "Target node name. Only allowed if the original VM is on shared storage."
        tags: [user_input, editable_only_in_app_template, enable_hints]
      VM ID:
        type: string
        description: "Proxmox VM Id that will be used as a source for deploying a VM."
        tags: [ user_input, editable_only_in_app_template, enable_hints ]
      Snapshot:
        type: string
        description: "The source VM snapshot name that will be used for deploying VM."
        tags: [ user_input, editable_only_in_app_template, enable_hints ]
      Behavior during save:
        type: string
        description: "Determines the VM behavior when the sandbox is saved.
        If Power off is selected, and the VM was powered on before the save, 
        then the VM will shut down for the duration of the save, 
        and then be powered on at the end."
        constraints:
          - valid_values: [ "Remain Powered On", "Power Off", "Inherited" ]
        default: "Inherited"
        tags: [ user_input ]
      Auto Power On:
        type: boolean
        description: "Enables the automatic power on of an app following its deployment during reservation Setup."
        default: true
        tags: [user_input]
      Auto Power Off:
        type: boolean
        description: "Enables the automatic power off of an app during reservation Teardown."
        default: true
        tags: []
      Wait for IP:
        type: boolean
        description: "If set to False the deployment will not wait for the VM to get an IP."
        default: true
        tags: [user_input]
      Auto Delete:
        type: boolean
        description: "Enables automatic deletion of an app during reservation Teardown."
        default: true
        tags: []
      Autoload:
        type: boolean
        description: "Enables the automatic execution of the Autoload command during reservation Setup."
        default: true
        tags: [ user_input ]
      Refresh IP Timeout:
        type: integer
        description: "Timeout for waiting when obtaining IP address (in seconds)"
        default: 600
        tags: [ user_input ]
      Autogenerated Name:
        type: boolean
        description: "If true the name would be generated by the Shell, otherwise it would be the same as App name."
        default: true
        tags: [ user_input ]
    artifacts:
      icon:
        file: proxmox.png
        type: tosca.artifacts.File

  vendor.resource.Proxmox Instance From Container 2G:
    derived_from: cloudshell.nodes.CustomDeploymentOption
    properties:
      Target Node:
        type: string
        description: "Target node name. Only allowed if the original VM is on shared storage."
        tags: [user_input, editable_only_in_app_template, enable_hints]
      Container ID:
        type: string
        description: "Proxmox VM Id that will be used as a source for deploying a VM."
        tags: [ user_input, editable_only_in_app_template, enable_hints ]
      Snapshot:
        type: string
        description: "The source VM snapshot name that will be used for deploying VM."
        tags: []
      Behavior during save:
        type: string
        description: "Determines the VM behavior when the sandbox is saved.
        If Power off is selected, and the VM was powered on before the save, 
        then the VM will shut down for the duration of the save, 
        and then be powered on at the end."
        constraints:
          - valid_values: [ "Remain Powered On", "Power Off", "Inherited" ]
        default: "Inherited"
        tags: [ user_input ]
      Auto Power On:
        type: boolean
        description: "Enables the automatic power on of an app following its deployment during reservation Setup."
        default: true
        tags: [user_input]
      Auto Power Off:
        type: boolean
        description: "Enables the automatic power off of an app during reservation Teardown."
        default: true
        tags: []
      Wait for IP:
        type: boolean
        description: "If set to False the deployment will not wait for the VM to get an IP."
        default: true
        tags: [user_input]
      Auto Delete:
        type: boolean
        description: "Enables automatic deletion of an app during reservation Teardown."
        default: true
        tags: []
      Autoload:
        type: boolean
        description: "Enables the automatic execution of the Autoload command during reservation Setup."
        default: true
        tags: [ user_input ]
      Refresh IP Timeout:
        type: integer
        description: "Timeout for waiting when obtaining IP address (in seconds)"
        default: 600
        tags: [ user_input ]
      Autogenerated Name:
        type: boolean
        description: "If true the name would be generated by the Shell, otherwise it would be the same as App name."
        default: true
        tags: [ user_input ]
    artifacts:
      icon:
        file: proxmox.png
        type: tosca.artifacts.File

  vendor.resource.Proxmox Instance From Template 2G:
    derived_from: cloudshell.nodes.CustomDeploymentOption
    properties:
      Target Node:
        type: string
        description: "Target node name. Only allowed if the original VM is on shared storage."
        tags: [user_input, editable_only_in_app_template, enable_hints]
      Template ID:
        type: string
        description: "Proxmox Template Id that will be used as a source for deploying a VM."
        tags: [ user_input, editable_only_in_app_template, enable_hints ]
      Clone Mode:
        type: string
        description: "Instance clone mode. Full - create a full copy of all disks."
        constraints:
          - valid_values: [ "Full", "Linked" ]
        default: "Linked"
        tags: [ user_input ]
      Behavior during save:
        type: string
        description: "Determines the VM behavior when the sandbox is saved. If Power off is selected, and the VM
        was powered on before the save, then the VM will shut down for the duration of the save, and then be
        powered on at the end."
        constraints:
          - valid_values: [ "Remain Powered On", "Power Off", "Inherited" ]
        default: "Inherited"
        tags: [ user_input ]
      Auto Power On:
        type: boolean
        description: "Enables the automatic power on of an app following its deployment during reservation Setup."
        default: true
        tags: [user_input]
      Auto Power Off:
        type: boolean
        description: "Enables the automatic power off of an app during reservation Teardown."
        default: true
        tags: []
      Wait for IP:
        type: boolean
        description: "If set to False the deployment will not wait for the VM to get an IP."
        default: true
        tags: [user_input]
      Auto Delete:
        type: boolean
        description: "Enables automatic deletion of an app during reservation Teardown."
        default: true
        tags: []
      Autoload:
        type: boolean
        description: "Enables the automatic execution of the Autoload command during reservation Setup."
        default: true
        tags: [ user_input ]
      Refresh IP Timeout:
        type: integer
        description: "Timeout for waiting when obtaining IP address (in seconds)"
        default: 600
        tags: [ user_input ]
      Autogenerated Name:
        type: boolean
        description: "If true the name would be generated by the Shell, otherwise it 
        would be the same as App name."
        default: true
        tags: [ user_input ]
    artifacts:
      icon:
        file: proxmox.png
        type: tosca.artifacts.File